### ISSUE TITLE
if openswan support linux4.14,when i make,Something went wrong,such as ipsec_tunnel.c:148:9: error: too few arguments to function 'dst_output' return dst_output(skb);

### ISSUE THREAD

**Issue by missionceo** [xelerance/Openswan#392]
Whether openswan only supports 2.6 kernels

**Comment by missionceo** [comment]
methods of compiling:make package/network/services/openswan/compile V=s

**Comment by mcr** [comment]
Hi, Openswan runs primarily on the inkernel ("NETKEY") kernel code, so it
works on 2.4, 2.6, 3.0, 4.0 and 5.0 kernels using that.
If you want to use KLIPS, then I recommend you use Libreswan.

**Comment by letoams** [comment]
Libreswan 3.31 will be the last release supporting KLIPS and it will introduce XFRMi support that replaces offering ipsec interfaces. KLIPS also only supports 3des and aes_cbc and not aes_gcm or chacha20_poly1305. So it is really dated.

Paul

**Comment by missionceo** [comment]
> Libreswan 3.31 will be the last release supporting KLIPS and it will introduce XFRMi support that replaces offering ipsec interfaces. KLIPS also only supports 3des and aes_cbc and not aes_gcm or chacha20_poly1305. So it is really dated. Paul Sent from mobile device
> […](#)
> On Aug 13, 2019, at 20:09, Michael Richardson ***@***.***> wrote: Hi, Openswan runs primarily on the inkernel ("NETKEY") kernel code, so it works on 2.4, 2.6, 3.0, 4.0 and 5.0 kernels using that. If you want to use KLIPS, then I recommend you use Libreswan. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

what is libreswan?and What's the difference between him and openswan?

**Comment by letoams** [comment]
Libreswan is a continuation of openswan due to a trademark dispute: 

https://nohats.ca/wordpress/openswan/

Libreswan has replaced openswan in RHEL/Centos/fedora, Debian/Ubuntu and openwrt

Libreswan is under active development: https://nohats.ca/swan.gif

**Comment by missionceo** [comment]
> Libreswan is a continuation of openswan due to a trademark dispute: https://nohats.ca/wordpress/openswan/ Libreswan has replaced openswan in RHEL/Centos/fedora, Debian/Ubuntu and openwrt Libreswan is under active development: https://nohats.ca/swan.gif
> […](#)
> On Aug 13, 2019, at 21:52, missionceo ***@***.***> wrote: Libreswan 3.31 will be the last release supporting KLIPS and it will introduce XFRMi support that replaces offering ipsec interfaces. KLIPS also only supports 3des and aes_cbc and not aes_gcm or chacha20_poly1305. So it is really dated. Paul Sent from mobile device … On Aug 13, 2019, at 20:09, Michael Richardson @.***> wrote: Hi, Openswan runs primarily on the inkernel ("NETKEY") kernel code, so it works on 2.4, 2.6, 3.0, 4.0 and 5.0 kernels using that. If you want to use KLIPS, then I recommend you use Libreswan. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. what is libreswan?and What's the difference between him and openswan? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

How to download this project?Does it compile directly in openwrt17

**Comment by mcr** [comment]
missionceo <notifications@github.com> wrote:
    > what is libreswan?and What's the difference between him and openswan?

libreswan is a (6yr old?) fork of Openswan that Paul Wouters made.
Openswan is a 15yr old fork of FreeSWAN that Xelerance continues to maintain
for commercial clients.
Strongswan is a 16yr old fork of FreeSWAN.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        |    IoT architect   [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [
