### ISSUE TITLE
Does not build with kernel 3.10

### ISSUE THREAD

**Issue by xelerance** [xelerance/Openswan#55]
Issue 1380 from www.openswan.org
Created by: **Dan Letz**
On Sat Aug  3 16:22:59 2013

_Priority: Normal_
_Status: Feedback_

Openswan needs updated to work with new procfs of Linux >= 3.10.x

**Comment by monstrenyatko** [comment]
I have the same problem on Raspberry Pi 2 with kernel **4.1.18-v7+** when I installing openswan-modules-dkms:

```
$ sudo apt-get install openswan-modules-dkms
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  openswan-modules-dkms
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/621 kB of archives.
After this operation, 2,495 kB of additional disk space will be used.
Selecting previously unselected package openswan-modules-dkms.
(Reading database ... 108879 files and directories currently installed.)
Unpacking openswan-modules-dkms (from .../openswan-modules-dkms_1%3a2.6.37-3+deb7u1_armhf.deb) ...
Setting up openswan-modules-dkms (1:2.6.37-3+deb7u1) ...
Loading new openswan-2.6.37 DKMS files...
First Installation: checking all kernels...
It is likely that 4.1.18-v7+ belongs to a chroot's host
Building for architecture armhf
Building initial module for 4.1.18-v7+
Error! Bad return status for module build on kernel: 4.1.18-v7+ (armhf)
Consult /var/lib/dkms/openswan/2.6.37/build/make.log for more information.
```

Compilation log:
```
  CC [M]  /var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.o
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1049:2: error: unknown type name 'read_proc_t'
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1050:2: error: unknown type name 'write_proc_t'
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1054:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1054:2: warning: (near initialization for 'proc_items[0].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1056:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1056:2: warning: (near initialization for 'proc_items[2].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1058:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1058:2: warning: (near initialization for 'proc_items[4].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1060:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1060:2: warning: (near initialization for 'proc_items[6].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1066:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1066:2: warning: (near initialization for 'proc_items[8].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1066:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1066:2: warning: (near initialization for 'proc_items[8].writething') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1067:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1067:2: warning: (near initialization for 'proc_items[9].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1067:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1067:2: warning: (near initialization for 'proc_items[9].writething') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1068:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1068:2: warning: (near initialization for 'proc_items[10].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1071:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1071:2: warning: (near initialization for 'proc_items[11].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1074:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1074:2: warning: (near initialization for 'proc_items[13].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1075:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1075:2: warning: (near initialization for 'proc_items[14].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1076:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1076:2: warning: (near initialization for 'proc_items[15].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1077:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1077:2: warning: (near initialization for 'proc_items[16].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1078:2: warning: initialization from incompatible pointer type [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1078:2: warning: (near initialization for 'proc_items[17].readthing') [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c: In function 'ipsec_proc_init':
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1152:5: error: implicit declaration of function 'create_proc_entry' [-Werror=implicit-function-declaration]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1152:10: warning: assignment makes pointer from integer without a cast [enabled by default]
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1155:9: error: dereferencing pointer to incomplete type
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1156:9: error: dereferencing pointer to incomplete type
/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.c:1157:9: error: dereferencing pointer to incomplete type
cc1: some warnings being treated as errors
scripts/Makefile.build:258: recipe for target '/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.o' failed
make[2]: *** [/var/lib/dkms/openswan/2.6.37/build/modobj26/ipsec_proc.o] Error 1
Makefile:1384: recipe for target '_module_/var/lib/dkms/openswan/2.6.37/build/modobj26' failed
make[1]: *** [_module_/var/lib/dkms/openswan/2.6.37/build/modobj26] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.1.18-v7+'
Makefile:449: recipe for target 'module26' failed
make: *** [module26] Error 2
make: Leaving directory '/var/lib/dkms/openswan/2.6.37/build'
```

**Comment by letoams** [comment]
Libreswan klips compiles on 4.x kernels

**Comment by simondeziel** [comment]
@monstrenyatko we are working on extending KLIPS support to newer kernels. 
In the meantime, maybe you can use the netkey stack that doesn't require any DKMS module?
