### ISSUE TITLE
KLIPS kernel module on Centos 7 kernel 3.10 error: ‘struct neigh_parms’ has no member named ‘ucast_probes’

### ISSUE THREAD

**Issue by robertlabrie** [xelerance/Openswan#177]
Hi,

This kernel module doesn't build on Centos 7 with a 3.10.0-327.10.1.el7.x86_64 Kernel. I get error: ‘struct neigh_parms’ has no member named ‘ucast_probes’.

Is this a known issue? Am I doing something wrong?

Thanks,
Rob

--- log ---
[root@ip-10-1-0-121 openswan-2.6.46]# make KERNELSRC=/lib/modules/`uname -r`/build module minstall
make module26
make[1]: Entering directory `/usr/src/openswan-2.6.46'
make[2]: Entering directory `/usr/src/openswan-2.6.46'
mkdir -p /usr/src/openswan-2.6.46/modobj26
echo ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/des/*.S /usr/src/openswan-2.6.46/modobj26
ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/des/dx86unix.S /usr/src/openswan-2.6.46/modobj26
(rm -f /usr/src/openswan-2.6.46/modobj26/des; mkdir -p /usr/src/openswan-2.6.46/modobj26/des && cd /usr/src/openswan-2.6.46/modobj26/des && ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/des/* . && ln -s -f Makefile.fs2_6 Makefile)
(rm -f /usr/src/openswan-2.6.46/modobj26/aes; mkdir -p /usr/src/openswan-2.6.46/modobj26/aes && cd /usr/src/openswan-2.6.46/modobj26/aes && ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/aes/* . && ln -s -f Makefile.fs2_6 Makefile)
mkdir -p /usr/src/openswan-2.6.46/modobj26/aes
cp /usr/src/openswan-2.6.46/packaging/makefiles/module26.make /usr/src/openswan-2.6.46/modobj26/Makefile
echo "# "                        >> /usr/src/openswan-2.6.46/modobj26/Makefile
echo "# Local Variables: "       >> /usr/src/openswan-2.6.46/modobj26/Makefile
echo "# compile-command: \"make -C /usr/src/openswan-2.6.46 ARCH=x86_64 KERNELSRC=/lib/modules/3.10.0-327.10.1.el7.x86_64/build MOD26BUILDDIR=/usr/src/openswan-2.6.46/modobj26 module26\""         >> /usr/src/openswan-2.6.46/modobj26/Makefile
echo "# End: "       >> /usr/src/openswan-2.6.46/modobj26/Makefile
ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/match*.S /usr/src/openswan-2.6.46/modobj26
make[2]: Leaving directory `/usr/src/openswan-2.6.46'
make -C /lib/modules/3.10.0-327.10.1.el7.x86_64/build  BUILDDIR=/usr/src/openswan-2.6.46/modobj26 SUBDIRS=/usr/src/openswan-2.6.46/modobj26 MODULE_DEF_INCLUDE=/usr/src/openswan-2.6.46/packaging/linus/config-all.h MODULE_DEFCONFIG=/usr/src/openswan-2.6.46/linux/net/ipsec/defconfig  MODULE_EXTRA_INCLUDE= ARCH=x86_64 V= modules
make[2]: Entering directory `/usr/src/kernels/3.10.0-327.10.1.el7.x86_64'
ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/ipsec_init.c /usr/src/openswan-2.6.46/modobj26/ipsec_init.c
  CC [M]  /usr/src/openswan-2.6.46/modobj26/ipsec_init.o
ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/ipsec_sa.c /usr/src/openswan-2.6.46/modobj26/ipsec_sa.c
  CC [M]  /usr/src/openswan-2.6.46/modobj26/ipsec_sa.o
ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/ipsec_radij.c /usr/src/openswan-2.6.46/modobj26/ipsec_radij.c
  CC [M]  /usr/src/openswan-2.6.46/modobj26/ipsec_radij.o
ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/radij.c /usr/src/openswan-2.6.46/modobj26/radij.c
  CC [M]  /usr/src/openswan-2.6.46/modobj26/radij.o
ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/ipsec_life.c /usr/src/openswan-2.6.46/modobj26/ipsec_life.c
  CC [M]  /usr/src/openswan-2.6.46/modobj26/ipsec_life.o
ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/ipsec_proc.c /usr/src/openswan-2.6.46/modobj26/ipsec_proc.c
  CC [M]  /usr/src/openswan-2.6.46/modobj26/ipsec_proc.o
ln -s -f /usr/src/openswan-2.6.46/linux/net/ipsec/ipsec_tunnel.c /usr/src/openswan-2.6.46/modobj26/ipsec_tunnel.c
  CC [M]  /usr/src/openswan-2.6.46/modobj26/ipsec_tunnel.o
/usr/src/openswan-2.6.46/modobj26/ipsec_tunnel.c: In function ‘ipsec_tunnel_neigh_setup_dev’:
/usr/src/openswan-2.6.46/modobj26/ipsec_tunnel.c:1386:18: error: ‘struct neigh_parms’ has no member named ‘ucast_probes’
                 p->ucast_probes = 0;
                  ^
/usr/src/openswan-2.6.46/modobj26/ipsec_tunnel.c:1387:18: error: ‘struct neigh_parms’ has no member named ‘mcast_probes’
                 p->mcast_probes = 0;
                  ^
make[3]: *** [/usr/src/openswan-2.6.46/modobj26/ipsec_tunnel.o] Error 1
make[2]: *** [_module_/usr/src/openswan-2.6.46/modobj26] Error 2
make[2]: Leaving directory `/usr/src/kernels/3.10.0-327.10.1.el7.x86_64'
make[1]: *** [module26] Error 2
make[1]: Leaving directory `/usr/src/openswan-2.6.46'
make: *** [module] Error 2

**Comment by rosada** [comment]
I am facing the same issue, anyone have the solution?
